Test CI

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -65,8 +65,12 @@ jobs:
             )
           fi
 
-          # NOTE: Skip the buildbuddy sidecar on linux where the machine is too small.
-          # TODO: Remove this once upstream has fixed the issue.
-          BB_DISABLE_SIDECAR=1 ./bazelw test --config=ci --config=public-cache "${args[@]}" --build_tag_filters=-skip-external-ci-${{ matrix.os }},-requires-network --test_tag_filters=-skip-external-ci-${{ matrix.os }},-requires-network -- //...
+          ./bazelw mod tidy
+          git diff --exit-code -- ./MODULE.bazel ./MODULE.bazel.lock || {
+            echo "error: Changes detected: MODULE.bazel is out of date."
+            echo "Try running './bazelw mod tidy' and committing the changes."
+            exit 1
+          }
+
         env:
           BUILDBUDDY_TOKEN: ${{ secrets.BUILDBUDDY_TOKEN }}
